var SASS_ALL = 'app/all.scss';
var SASS_PATTERN = 'app/modules/**/*.scss';

var gulp = require('gulp');
var browserSync = require('browser-sync').create();

// Generates the Sass import file used to create all.css
gulp.task('sass-gen', function () {
    var glob = require('glob');
    var imports = [
        '// ' + new Date().toISOString(),
        '// Generated by sass-gen task in gulpfile.js.  Do not edit.'
    ];

    glob(SASS_PATTERN, function (err, files) {
        for (var i = 0; i < files.length; i++) {
            imports.push('@import "' + files[i] + '";');
        }

        var fs = require('fs');
        fs.writeFileSync(SASS_ALL, imports.join('\r\n'));
    });
});

// Creates all.css and all.min.css
gulp.task('sass', ['sass-gen'], function () {
    var sass = require('gulp-sass');
    var cssmin = require('gulp-cssmin');
    var header = require('gulp-header');
    var rename = require('gulp-rename');
    var banner = '/* Generated at ' + new Date().toISOString() + '.  Do not edit. */\r\n';
    return gulp.src(SASS_ALL)
        .pipe(sass())
        .pipe(header(banner))
        .pipe(gulp.dest('app'))
        .pipe(cssmin())
        .pipe(rename({ suffix: '.min' }))
        .pipe(header(banner))
        .pipe(gulp.dest('app'));
});

// Creates all.js and all.min.js
gulp.task('script', function () {
    var sass = require('gulp-sass');
    var cssmin = require('gulp-cssmin');
    var header = require('gulp-header');
    var rename = require('gulp-rename');
    var banner = '/* Generated at ' + new Date().toISOString() + '.  Do not edit. */\r\n';
    return gulp.src(SASS_ALL)
        .pipe(sass())
        .pipe(header(banner))
        .pipe(gulp.dest('app'))
        .pipe(cssmin())
        .pipe(rename({ suffix: '.min' }))
        .pipe(header(banner))
        .pipe(gulp.dest('app'));
});

// Create the watch, ensuring the browserSync and sass tasks are complete
gulp.task('watch', ['browserSync', 'sass'], function () {
    gulp.watch(SASS_PATTERN, ['sass']);
    gulp.watch('*.html', browserSync.reload);
    gulp.watch('app/all.min.css', function () { browserSync.reload({ stream: true }) });
    gulp.watch('app/all.min.js', browserSync.reload);    
});

gulp.task('browserSync', function() {
    browserSync.init({
        server: { baseDir: '' }
    });
});